language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "python setup.py -q install"
# command to run tests
script: 
  - nosetests
  - coverage run --source openrunlog setup.py test
after_success: coveralls
matrix:
    allow_failures:
        - python: "2.6"
        - python: "3.2"
        - python: "3.3"
    fast_finish: true
