language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py -q install"
# command to run tests
script: 
  - nosetests
  - coverage run --source openrunlog setup.py test
after_success: coveralls
